version: '3.7'
services:
  terminal:
    image: vergissberlin/andrelademann-de-terminal
    build: .
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - 1337:1337
      - 8088:8088
    environment:
      - NODE_ENV=production
    expose:
      - 1337
      - 8088